sudo: false
language: node_js
node_js:
  - '--lts'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_script:
  - npm prune
  - yarn build
script:
  - yarn test
after_script:
  - yarn report-coverage
  - yarn semantic-release
